name: PR Test

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - closed
      - ready_for_review
      - labeled
      - unlabeled
      - review_requested
      - review_request_removed
      - assigned
      - unassigned
      - locked
      - unlocked
      - converted_to_draft

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This is a test comment.
            It will be updated if it already exists.
