name: PR Test

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review, labeled ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Comment PR
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: Tests failed, please check your code.
        token: ${{ secrets.GITHUB_TOKEN }}
